services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
